1. WEMBABAZI VIVIAN RITAH       2023/DSCE/0093/SS
2. NAMARA RACHEAL               2023/DCSE/0071/SS
3. ACHOLA GLORIA FORTUNATE      2023/DCSE/0001/SS
4. NASIRUMBI MARTHA             2023/DSCE/0084/SS
5. NANTEZA DORCUS               2023/DSCE/0080/SS
6. NANTEZA ANGELLA              2023/DSCE/00106/SS
7. MBABAZI ANGEL                2023/DSCE/0040/SS
8. NAMUKOSE JOLLINE EDRIANA     2023/DSCE/0077/SS
REFERENCES: Shecodes Athena

MATRIX DECOMPOSITION

Matrix decomposition, also known as matrix factorization, involves describing a given matrix using its constituent elements

Singular-Value Decomposition
The Singular-Value Decomposition, or SVD for short, is a matrix decomposition method for reducing a matrix to its constituent parts in order to make certain subsequent matrix calculations simpler.

For the case of simplicity we will focus on the SVD for real-valued matrices and ignore the case for complex numbers.

A = U . Sigma . V^T
Where A is the real m x n matrix that we wish to decompose, U is an m x m matrix, Sigma (often represented by the uppercase Greek letter Sigma) is an m x n diagonal matrix, and V^T is the  transpose of an n x n matrix where T is a superscript.

LU Decomposition (LU factorization):

LU decomposition factors a matrix into the product of a lower triangular matrix (L) and an upper triangular matrix (U).
A = LU, where A is the original matrix.
QR Decomposition (QR factorization):

QR decomposition factors a matrix into the product of an orthogonal matrix (Q) and an upper triangular matrix (R).
A = QR, where A is the original matrix.

Singular-Value Decomposition

In this example, we first import the numpy library and create a sample matrix A. Then, we use the np.linalg.svd function to perform Singular Value Decomposition. This function returns three matrices: U, S, and Vt.

U contains the left singular vectors.
S contains the singular values as a 1D array. To obtain a diagonal matrix, we use np.diag(S).
Vt contains the right singular vectors transposed.
You can run this code in a Python environment with NumPy installed. Keep in mind that this is just an example of SVD, and similar code structures would be used for other types of matrix decompositions, with adjustments based on the specific decomposition method you're using.

In [1]:
# Singular-value decomposition
#The example below defines a 3×2 matrix and calculates the Singular-value decomposition.
from numpy import array
from scipy.linalg import svd #Scipy is a scientific computing for python & imports all functions from numpy 
#and linalg it means linear algebra, svd Singular-Value Decomposition
# lets define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
# SVD
#Where A is the real m x n matrix that we wish to decompose, 
# U is an m x m matrix, Sigma is an m x n diagonal matrix, 
# and V^T is the  transpose of an n x n matrix where T is a superscript.
U, s, VT = svd(A)
print(U)
print(s)
print(VT)

[[1 2]
 [3 4]
 [5 6]]
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [1]:
# QR decomposition
from numpy import array
from numpy.linalg import qr
# define a 3x2 matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
# QR decomposition
Q, R = qr(A, 'complete')
print(Q)
print(R)
# reconstruct
B = Q.dot(R)
print(B)

[[1 2]
 [3 4]
 [5 6]]
[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]
[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [4]:
import numpy as np
#define a martix
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

# performm SVD
U, S, VT = np.linalg.svd(A)

print(U)
print(S)
print(VT)

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [3]:
# LU decomposition
from numpy import array
from scipy.linalg import lu
# define a square matrix
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)
# LU decomposition
P, L, U = lu(A)
print(P)
print(L)
print(U)
# reconstruct
B = P.dot(L).dot(U)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
[[7.         8.         9.        ]
 [0.         0.85714286 1.71428571]
 [0.         0.         0.        ]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
